title: Yaswanth Nadavadi
logo: /Assets/headshot_circle.png
description: Results-Driven Data Analyst with experience in Python, SQL, and data visualization tools like Tableau and Power BI. Strong
             background in decision-making and Statistical analysis. Passionate about uncovering insights from complex datasets
             to drive business strategies. Strong problem-solving skills with a keen eye for detail and data accuracy.
#show_downloads: true
#theme: jekyll-theme-minimal
